apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: maeq4v7s8-nodejs
  janus-idp.io/tekton: maeq4v7s8-nodejs
  backstage.io/kubernetes-id: maeq4v7s8-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: maeq4v7s8-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
